In [1]:
import torch

In [3]:
x = torch.rand(3, requires_grad=True)
print(x)

tensor([0.6492, 0.6664, 0.8898], requires_grad=True)


In [4]:
y = x + 2
print(y)

tensor([2.6492, 2.6664, 2.8898], grad_fn=<AddBackward0>)


In [7]:
z = y*y*2
z = z.mean()
print(z)

tensor(14.9859, grad_fn=<MeanBackward0>)


In [8]:
z.backward() # dz/dx
print(x.grad)

tensor([3.5323, 3.5552, 3.8530])


In [11]:
z = y*y*2
print(z)

v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)
z.backward(v) # dz/dx
print(x.grad)

tensor([14.0369, 14.2192, 16.7015], grad_fn=<MulBackward0>)
tensor([ 4.5920, 14.2207,  3.8646])


In [12]:
# Preventing gradient history

# x.requires_grad_()
# x.detach()
# with torch.no_grad():

tensor([0.4021, 0.2916, 0.6924], requires_grad=True)


In [15]:
x = torch.rand(3, requires_grad=True)
print(x)

# x.requires_grad_()
x.requires_grad_(False)
print(x)

tensor([0.5472, 0.3338, 0.4122], requires_grad=True)
tensor([0.5472, 0.3338, 0.4122])


In [19]:
x = torch.rand(3, requires_grad=True)
print(x)

# x.detach()
y = x.detach()
print(y)

tensor([0.0595, 0.9661, 0.7496], requires_grad=True)
tensor([0.0595, 0.9661, 0.7496])


In [20]:
x = torch.rand(3, requires_grad=True)
print(x)

# with torch.no_grad():
with torch.no_grad():
    y = x + 2
    print(y)

tensor([0.1902, 0.8101, 0.8159], requires_grad=True)
tensor([2.1902, 2.8101, 2.8159])


In [25]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(2):
    model_output = (weights*3).sum()
    
    model_output.backward()
    
    print(weights.grad)
    
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


# Summary
weights = torch.ones(4, requires_grad=True) # requires_grad

z.backward() # Calculate gradients calling backward() function 

"""Before we want to do the next opertaion or the next iteration in our optimization steps we must empty our gradient"""
weights.grad.zero_()