In [1]:
import torch
import numpy as np

x = torch.empty(1)
print(x)

tensor([0.])


In [2]:
# 1D tensor
x = torch.empty(3)
print(x)

tensor([0., 0., 0.])


In [3]:
# 2D tensor
x = torch.empty(2, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [4]:
# 3D tensor
x = torch.empty(2, 2, 3)
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [5]:
# Tensor with random values
x = torch.rand(2, 2)
print(x)

tensor([[0.7251, 0.9912],
        [0.0709, 0.3154]])


In [6]:
x = torch.zeros(2, 2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [7]:
x = torch.ones(2, 2, dtype=torch.float16)
print(x)
print(x.dtype)
print(x.size())

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)
torch.float16
torch.Size([2, 2])


In [8]:
# Python list to tensor
x = torch.tensor([2.5, 0.1])
print(x)
print(x.dtype)

tensor([2.5000, 0.1000])
torch.float32


In [9]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

tensor([[0.2290, 0.2272],
        [0.5261, 0.1995]])
tensor([[0.2068, 0.3838],
        [0.1947, 0.6012]])


In [10]:
z = x + y # Element-wise addition
print(z)

tensor([[0.4358, 0.6110],
        [0.7208, 0.8008]])


In [11]:
# Or
z = torch.add(x, y)
print(z)

tensor([[0.4358, 0.6110],
        [0.7208, 0.8008]])


In [12]:
# In-place element-wise addition
y.add_(x)
print(y)

tensor([[0.4358, 0.6110],
        [0.7208, 0.8008]])


In [13]:
z = x - y
print(z)
z = torch.sub(x, y)
print(z)

tensor([[-0.2068, -0.3838],
        [-0.1947, -0.6012]])
tensor([[-0.2068, -0.3838],
        [-0.1947, -0.6012]])


In [14]:
z = x * y
print(z)
z = torch.mul(x, y)
print(z)

tensor([[0.0998, 0.1388],
        [0.3792, 0.1598]])
tensor([[0.0998, 0.1388],
        [0.3792, 0.1598]])


In [15]:
z = x / y
print(z)
z = torch.div(x, y)
print(z)

tensor([[0.5254, 0.3718],
        [0.7299, 0.2492]])
tensor([[0.5254, 0.3718],
        [0.7299, 0.2492]])


In [16]:
x = torch.rand(5, 3)
print(x)
print(x[:, 0]) # All rows and 0th column

tensor([[0.3031, 0.8711, 0.9136],
        [0.8778, 0.2895, 0.7447],
        [0.4469, 0.0184, 0.6383],
        [0.6679, 0.0250, 0.9746],
        [0.8987, 0.6442, 0.9899]])
tensor([0.3031, 0.8778, 0.4469, 0.6679, 0.8987])


In [17]:
print(x[1, :]) # 1st row and all columns

tensor([0.8778, 0.2895, 0.7447])


In [18]:
print(x[2, 0].item()) # function item could be applied only on single tensor

0.446908175945282


In [19]:
x = torch.rand(4, 4)
print(x)

tensor([[0.2894, 0.9967, 0.0796, 0.5820],
        [0.2949, 0.4058, 0.1640, 0.8944],
        [0.2461, 0.1427, 0.9027, 0.5144],
        [0.1057, 0.7314, 0.0916, 0.7229]])


In [20]:
# Resizing tensors
y = x.view(16) # 1D vector
print(y)

tensor([0.2894, 0.9967, 0.0796, 0.5820, 0.2949, 0.4058, 0.1640, 0.8944, 0.2461,
        0.1427, 0.9027, 0.5144, 0.1057, 0.7314, 0.0916, 0.7229])


In [21]:
y = x.view(-1, 8) #PyTorch can figure out the right value
print(y)
print(y.size())

tensor([[0.2894, 0.9967, 0.0796, 0.5820, 0.2949, 0.4058, 0.1640, 0.8944],
        [0.2461, 0.1427, 0.9027, 0.5144, 0.1057, 0.7314, 0.0916, 0.7229]])
torch.Size([2, 8])


In [22]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [23]:
# Tensor to numpy
b = a.numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [24]:
# Numpy to tensor
a = np.ones(5)
print(a)
print(type(a))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [25]:
b = torch.from_numpy(a)
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
<class 'torch.Tensor'>


In [26]:
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
